ProjectManagementSystemMVC/Controllers/ProjectController.cs
using Domain.Models;
using Domain.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectManagementSystemMVC.Areas.Identity.Data;
using ProjectManagementSystemMVC.Models.ProjectTaskViewModel;
using ProjectManagementSystemMVC.Models.ProjectViewModels;
using ProjectManagementSystemMVC.Models.UserViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectManagementSystemMVC.Controllers
{
    public class ProjectController : BaseController
    {
        private readonly IProjectStore _projectStore;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ProjectController(IProjectStore projectStore, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager) : base(userManager)
        {
            _projectStore = projectStore;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var projects = _projectStore.GetAll().Select(x => new ProjectDetailViewModel
            {
                Id = x.Id,
                ProjectName = x.ProjectName,
                ProjectCode = x.ProjectCode
            });

            var model = new ProjectIndexViewModel
            {
                Projects = projects
            };

            ViewBag.IsAdmin = IsAdmin();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(string id)
        {
            var project = await _projectStore.GetByIdAsync(id);
                                                  
            var tasks = project.Tasks.Select(c => new ProjectTaskDetailViewModel
            {
                TaskName = c.Name,               
                Status = c.Statuses.ToString(),
                Progress = c.Progress,
                Description = c.Description,
                Deadline = c.Deadline,
                UserName = c.User.UserName
            }).ToList();

            var model = new ProjectDetailViewModel
            {
                Id = project.Id,
                ProjectName = project.ProjectName,               
                Tasks = tasks,
                ProjectCode = project.ProjectCode
            };
                    
            return View(model);
        }

        [Authorize(Policy = "ManagerAccess")]
        [HttpGet]
        public IActionResult Create()
        {
            var users = _userManager.GetUsersInRoleAsync("Project Manager").Result.Select(user => new UserDetailViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Username = user.UserName,
                Email = user.Email
            }).ToList();

            var model = new ProjectDetailViewModel(10)
            {
                Users = users                
            };

            return View(model);
        }

        [Authorize(Policy = "ManagerAccess")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectDetailViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var projectManager = _userManager.Users.SingleOrDefault(x => x.Id == model.ProjectManagerId);

            await _projectStore.Add(new Project
            {
                ProjectName = model.ProjectName,
                ProjectManager = projectManager,
                ProjectCode = model.ProjectCode
            });;

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "AdminAccess")]
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var project = await _projectStore.GetByIdAsync(id);

            if (project == null)
            {
                throw new ApplicationException($"Unable to load project.");
            }

            var users = _userManager.GetUsersInRoleAsync("Project Manager").Result.Select(user => new UserDetailViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Username = user.UserName,
                Email = user.Email
            }).ToList();

            var projectManager = project.ProjectManager.UserName;

            var model = new ProjectEditViewModel
            {
                Id = project.Id,
                ProjectName = project.ProjectName,
                Users = users,
                CurrentProjectManger = projectManager,
                ProjectCode = project.ProjectCode
            };

            return View(model);
        }

        [Authorize(Policy = "AdminAccess")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProjectEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var project = await _projectStore.GetByIdAsync(model.Id);
            var projectManager = _userManager.Users.SingleOrDefault(x => x.Id == model.ProjectManagerId);

            project.ProjectName = model.ProjectName;
            project.ProjectManager = projectManager;

            await _projectStore.Update(project);

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "AdminAccess")]
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var project = await _projectStore.GetByIdAsync(id);
            if (project == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new ProjectDeleteViewModel
            {
               Id = id,
               ProjectName = project.ProjectName,
                ProjectCode = project.ProjectCode
            };

            return View(model);
        }
        [Authorize(Policy = "AdminAccess")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ProjectDeleteViewModel model)
        {
            var project = await _projectStore.GetByIdAsync(model.Id);
            if (project == null)
            {
                return RedirectToAction(nameof(Index));
            }
            await _projectStore.Delete(project);

            return RedirectToAction(nameof(Index));
        }
    }
}

ProjectManagementSystemMVC/Controllers/ProjectTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Enums;
using Domain.Models;
using Domain.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using ProjectManagementSystemMVC.Areas.Identity.Data;
using ProjectManagementSystemMVC.Models.ApplicationRoleViewModels;
using ProjectManagementSystemMVC.Models.ProjectTaskViewModel;
using ProjectManagementSystemMVC.Models.ProjectViewModels;
using ProjectManagementSystemMVC.Models.UserViewModels;

namespace ProjectManagementSystemMVC.Controllers
{
    public class ProjectTaskController : BaseController
    {
        private readonly IProjectStore _projectStore;
        private readonly IProjectTaskStore _projectTaskStore;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ProjectTaskController(IProjectTaskStore projectTaskStore, IProjectStore projectStore, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager) : base(userManager)
        {
            _projectTaskStore = projectTaskStore;
            _projectStore = projectStore;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string id)
        {
            var project = await _projectStore.GetByIdAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            var tasks = project.Tasks.Select(x => new ProjectTaskDetailViewModel
            {
                Id = x.Id,
                TaskName = x.Name,
                UserName = x.User.UserName,
                Status = x.Statuses.ToString(),
                Progress = x.Progress,
                Deadline = x.Deadline,
                Description = x.Description,
                UserId = x.User.Id
            }).ToList();

            var model = new ProjectTaskIndexViewModel
            {
                ProjectId = id,
                ProjectName = project.ProjectName,
                Tasks = tasks
            };

            ViewBag.CurrentUserId = GetCurrentUser().Id;
            ViewBag.IsAdmin = IsAdmin();

            return View(model);
        }
        [Authorize(Policy = "ManagerAccess")]
        [HttpGet]
        public async Task<IActionResult> AddTask(string id)
        {

            var users = _userManager.Users.Select(user => new UserDetailViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Username = user.UserName,
                Email = user.Email
            }).ToList();

            var project = await _projectStore.GetByIdAsync(id);

            var model = new CreateTaskViewModel
            {
                ProjectId = id,
                Users = users,
                ProjectName = project.ProjectName
            };

            return View(model);
        }

        [Authorize(Policy = "ManagerAccess")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTask(CreateTaskViewModel model)
        {
            var project = await _projectStore.GetByIdAsync(model.ProjectId);

            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == model.UserId);

            var task = new ProjectTask
            {
                Name = model.TaskName,
                Project = project,
                User = user,
                Statuses = Status.New,
                Deadline = model.Deadline
            };

            await _projectTaskStore.AddTask(task);

            return RedirectToAction(nameof(Index), new { project.Id });
        }

        [Authorize(Policy = "DeveloperAccess")]
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {            

            var projectTask = await _projectTaskStore.GetProjectTaskById(id);

            var currentUser = projectTask.User.Id;

            if (projectTask == null)
            {
                throw new ApplicationException($"Unable to find Task.");
            }

            var users = _userManager.Users.Select(user => new UserDetailViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Username = user.UserName,
                Email = user.Email
            }).ToList();

            var model = new ProjectTaskEditViewModel
            {                
                TaskId = id,
                Users = users,
                UserId = currentUser,
                TaskName = projectTask.Name,
                Deadline = projectTask.Deadline,
                Description = projectTask.Description,
                ProjectId = projectTask.Project.Id,
                Progress = projectTask.Progress
            };

            ViewBag.IsManager = IsManager();
            ViewBag.IsDeveloper = IsDeveloper();
            ViewBag.IsAdmin = IsAdmin();

            return View(model);
        }

        [Authorize(Policy = "DeveloperAccess")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProjectTaskEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            
            var projectTask = await _projectTaskStore.GetProjectTaskById(model.TaskId);
           
            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == model.UserId);

            projectTask.Name = model.TaskName;
            projectTask.User = user;
            projectTask.Statuses = model.Statuses;
            projectTask.Description = model.Description;
            projectTask.Deadline = model.Deadline;
            projectTask.Progress = model.Progress;

            await _projectTaskStore.Update(projectTask);

            return RedirectToAction(nameof(Index), new { projectTask.Project.Id });
        }
        [Authorize(Policy = "AdminAccess")]
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var projectTask = await _projectTaskStore.GetProjectTaskById(id);
            if (projectTask == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new ProjectTaskDeleteViewModel
            {
                Id = id,
                ProjectId = projectTask.Project.Id,
                TaskName = projectTask.Name,
                Statuses = projectTask.Statuses.ToString(),
                Deadline = projectTask.Deadline,
                UserName = projectTask.User.UserName
            };

            return View(model);
        }

        [Authorize(Policy = "AdminAccess")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ProjectTaskDeleteViewModel model)
        {
            
            var projectTask = await _projectTaskStore.GetProjectTaskById(model.Id);

            var id = projectTask.Project.Id;

            if (projectTask == null)
            {
                return RedirectToAction(nameof(Index));
            }
            await _projectTaskStore.Delete(projectTask);

            return RedirectToAction(nameof(Index), new { id });
        }
    }
}

ProjectManagementSystemMVC/Views/Project/Create.cshtml
@model ProjectManagementSystemMVC.Models.ProjectViewModels.ProjectDetailViewModel
@{
    ViewData["Title"] = "Create";
}
<div class="container">
    <h2>@ViewData["Title"]</h2>
    <div class="row">
        <div class="col-md-5">            
            <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
                <h4>Create a new project.</h4>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ProjectName"></label>
                    <input asp-for="ProjectName" class="form-control" />
                    <span asp-validation-for="ProjectName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProjectCode"></label>
                    <input asp-for="ProjectCode" class="form-control" readonly />
                    <span asp-validation-for="ProjectCode" class="text-danger"></span>
                </div>
                <select id="projectManagerId" name="projectManagerId" class="form-control" required>
                    <option value="">Select Manager</option>
                    @foreach (var user in Model.Users)
                    {
                        <option value="@user.Id">@user.Username</option>
                    }
                </select>
                <button type="submit" class="btn btn-success btn-block mt-4">Create</button>
            </form>            
        </div>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

ProjectManagementSystemMVC/Views/Project/Delete.cshtml
@model ProjectManagementSystemMVC.Models.ProjectViewModels.ProjectDeleteViewModel

@{
    ViewData["Title"] = "Delete Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="container">
        <h1>@ViewData["Title"]</h1>
        <hr />
        <p class="text-danger">@ViewData["ErrorMessage"]</p>
        <h5>Are you sure you want to delete this project?</h5>
        <hr />
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input asp-for="Id" type="hidden" />
                    <div class="form-group">
                        <label asp-for="ProjectName"></label>
                        <input asp-for="ProjectName" class="form-control" readonly />
                        <span asp-validation-for="ProjectName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectCode"></label>
                        <input asp-for="ProjectCode" class="form-control" disabled />
                        <span asp-validation-for="ProjectCode" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-danger btn-block">Delete</button>
                    <a asp-action="Index" class="btn btn-block btn-outline-primary">Back to List</a>
                </div>
            </div>
        </form>
    </div>

ProjectManagementSystemMVC/Views/Project/Detail.cshtml
@model ProjectManagementSystemMVC.Models.ProjectViewModels.ProjectDetailViewModel
@{
    ViewData["Title"] = "Project Details";
}
<div class="container">
    <div class="row">
        <div class="col-12">
            <section>
                <h2>@ViewData["Title"]</h2>
                <hr />
                <div class="row">
                    <div class="col">
                        <h5>Project Name: <strong>@Model.ProjectName</strong></h5>
                    </div>
                </div>
                <hr />
                <div class="row mt-3">
                    <div class="col-12">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Task Name</th>
                                    <th>User</th>
                                    <th>Status</th>
                                    <th>Progress</th>
                                    <th>Description</th>
                                    <th>Deadline</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var task in Model.Tasks)
                                {
                                    <tr>
                                        <td>@task.TaskName</td>
                                        <td>@task.UserName</td>
                                        <td>@task.Status</td>
                                        <td>@task.Progress</td>
                                        <td>@task.Description</td>
                                        <td>@task.Deadline</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>  
                <div class="row">
                    <div class="col-4">
                        <a asp-action="Index" class="btn btn-outline-primary btn-block">Back to List</a>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

ProjectManagementSystemMVC/Views/Project/Edit.cshtml
@model ProjectManagementSystemMVC.Models.ProjectViewModels.ProjectEditViewModel
@{
    ViewData["Title"] = "Edit Project";
}
<div class="container">    
    <div class="row">
        <div class="col-md-6">
            <section>
                <h2> @ViewData["Title"]</h2>
                <hr />                
                <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="ProjectName"></label>
                        <input asp-for="ProjectName" class="form-control" />
                        <span asp-validation-for="ProjectName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectCode"></label>
                        <input asp-for="ProjectCode" class="form-control" readonly />
                        <span asp-validation-for="ProjectCode" class="text-danger"></span>
                    </div>
                    <select id="projectManagerId" name="projectManagerId" class="form-control" required>
                        <option selected="selected">@Model.CurrentProjectManger</option>
                        @foreach (var user in Model.Users)
                        {
                            <option value="@user.Id">@user.Username</option>
                        }
                    </select>
                    <button type="submit" class="btn btn-success btn-block mt-4">Update</button>
                    <a asp-action="Index" class="btn btn-outline-primary btn-block">Back to List</a>
                </form>
            </section>
        </div>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

ProjectManagementSystemMVC/Views/Project/Index.cshtml
@model ProjectManagementSystemMVC.Models.ProjectViewModels.ProjectIndexViewModel
@{
    ViewData["Title"] = "Projects";
}

<div class="container">
    <h2>@ViewData["Title"]</h2>

    <div class="row">
        <div class="col-md-12">
            <section>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Project Code</th>
                            <th class="text-center" style="width: 30%">Actions</th>                           
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var project in Model.Projects)
                        {
                            <tr>
                                <td>@project.ProjectName</td>                              
                                <td>@project.ProjectCode</td>                              
                                <td class="text-center">
                                    @if (ViewBag.IsAdmin == true)
                                    {
                                        <a asp-controller="Project" asp-action="Edit" asp-route-id="@project.Id" class="btn btn-success">Edit</a>
                                        <a asp-controller="ProjectTask" asp-action="Index" asp-route-id="@project.Id" class="btn btn-success">Tasks</a>
                                        <a asp-controller="Project" asp-action="Detail" asp-route-id="@project.Id" class="btn btn-success">Details</a>
                                        <a asp-controller="Project" asp-action="Delete" asp-route-id="@project.Id" class="btn btn-danger">Delete</a>
                                    } else {
                                        <a asp-controller="Project" asp-action="Detail" asp-route-id="@project.Id" class="btn btn-success">Details</a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a asp-controller="Project" asp-action="Create" class="btn btn-primary">Create New</a>
            </section>
        </div>
    </div>
</div>